# ----
# Site

title: KAT Data Labs
url: "https://katdl.com"
baseurl:
lang: en-us

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/site-icons/jemurai-square.png
description: KAT Data Labs
author:
  name: Matt Konda
  email: mattkonda@hey.com
  twitter: 
social:
  name: 
  links:
    - https://github.com/katdl/
    - https://katdl.com/

# Podcast info
collections:
# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/blog/:num/"
permalink: /:year/:month/:day/:slug/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
